/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.flowchart.console;

import core.data.Fsymbol;
import i18n.Fi18N;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author zulu
 */
public class Console extends javax.swing.JPanel {

    static ImageIcon icon = Fi18N.loadIcon(Fi18N.get("DIALOG.flowchartMenu.icon"), 24);

    /**
     * Creates new form pnConsole
     */
    public Console() {
        initComponents();
        clear();
    }
    
    public void setVerticalOrientation(){
        spltIO.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
    }

    public void setDividerLocation(int location) {
        spltIO.setDividerLocation(location);
    }

    ArrayList<String> inputMemory = new ArrayList<>();

    /**
     * read a variable from a input text our sohw an option pane
     *
     * @param symbol
     * @return
     */
    public String read(Fsymbol symbol, String help) {
        String var = help
                + "\n:::::::::::::::::::::::::::::\n"
                + symbol.getFullName()
                + "\n:::::::::::::::::::::::::::::\n"
                + symbol.getComments();

        if (txtInput.getText().isEmpty()) {
            var = (String) JOptionPane.showInputDialog(
                    null,
                    var.trim(),
                    Fi18N.get("READ.instruction.title"),
                    JOptionPane.PLAIN_MESSAGE,
                    icon,
                    null,
                    symbol.getTextValue());

//            var = JOptionPane.showInputDialog(null, symbol.getFullName());
        } else {
            //scan first line
            Scanner scanner = new Scanner(txtInput.getText());
            var = scanner.nextLine();
            //remove input
            txtInput.setText(txtInput.getText().substring(var.length()).trim());
        }
        if (var == null) {
            return var;
        }

        //memorize input
        inputMemory.add(var);
//        txtOutput.append(var + "\n");
        //return var
        return var;
    }

    public void write(String text) {
        txtOutput.append(text);
        txtOutput.setCaretPosition(txtOutput.getText().length());
        repaint();
    }

    public void begin() {
        txtOutput.setText("");
    }

    public void end() {
        StringBuilder txt = new StringBuilder();
        for (String inputMemory1 : inputMemory) {
            txt.append(inputMemory1 + "\n");
        }
        txtInput.setText(txt.toString().trim());
        inputMemory.clear();
    }

    public void clear() {
        // txtInput.setText("");
        txtOutput.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spltIO = new javax.swing.JSplitPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInput = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        spltIO.setDividerLocation(200);

        jScrollPane5.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        txtOutput.setEditable(false);
        txtOutput.setBackground(new java.awt.Color(0, 0, 0));
        txtOutput.setColumns(20);
        txtOutput.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtOutput.setForeground(new java.awt.Color(255, 255, 255));
        txtOutput.setRows(5);
        jScrollPane5.setViewportView(txtOutput);

        spltIO.setRightComponent(jScrollPane5);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));

        txtInput.setBackground(new java.awt.Color(204, 204, 204));
        txtInput.setColumns(20);
        txtInput.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtInput.setRows(5);
        jScrollPane2.setViewportView(txtInput);

        spltIO.setLeftComponent(jScrollPane2);

        add(spltIO, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane spltIO;
    private javax.swing.JTextArea txtInput;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables

    //::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    private static final long serialVersionUID = 201509071215L;
    //:::::::::::::::::::::::::::  Copyright(c) M@nso  2015  :::::::::::::::::::
    ///////////////////////////////////////////////////////////////////////////

}
