/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flowchart.decide;

import flowchart.decide.IfElse.IfThenElse;
import core.Memory;
import core.data.exception.FlowchartException;
import core.parser.tokenizer.BreakMarks;
import ui.FProperties;
import ui.flowchart.dialogs.Fdialog;
import ui.flowchart.dialogs.ShapeMenuDialog;
import i18n.Fi18N;
import flowchart.help.Help;
import flowchart.shape.MenuPattern;
import flowchart.shape.Fshape;
import flowchart.utils.Theme;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author ZULU
 */
public class MenuDecide extends ShapeMenuDialog implements MenuPattern {

    Fshape decision;
    String oldText;
    Memory memory;
    String INSTRUCTION;

    /**
     * Creates new form TerminatorMenu
     */
    public MenuDecide() {
        super("IF.instruction.title");
//        setUndecorated(true);
        initComponents();
        I18N();
        //::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
        //------------------------------------------------------------
        //Add key Listener to Text Fields
        txtExpressionShape.addKeyListener(getKeyListener(btOk, KeyEvent.VK_ENTER));
        txtExpressionShape.addKeyListener(getKeyListener(btCancel, KeyEvent.VK_ESCAPE));
        txtComments.addKeyListener(getKeyListener(btCancel, KeyEvent.VK_ESCAPE));
        //------------------------------------------------------------
        //::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    }

    public void I18N() {
        Fi18N.loadTabTile(tabMain, "MENU.comments", 0);
        Fi18N.loadTabTile(tabMain, "MENU.help", 1);
        Fi18N.loadButton(btOk, "BUTTON.accept", 24);
        Fi18N.loadButton(btCancel, "BUTTON.cancel", 24);
        Fi18N.loadButton(btHelp, "BUTTON.help", 16);

        lblHelp.setBackground(FProperties.decisionColor);
        txtComments.setToolTipText(Theme.toHtml(Fi18N.get("DECIDE.comments.help")));
    }

    @Override
    public void showDialog(Fshape shape, int x, int y) {

        
        if (shape instanceof IfThenElse) {
            INSTRUCTION = "IF";
            txtExpressionShape.setKeyword(IfThenElse.KEYWORD);
            this.decision = (IfThenElse) shape;
        } else if (shape instanceof While_Do) {
            INSTRUCTION = "WHILE";
            txtExpressionShape.setKeyword(While_Do.KEYWORD);
            this.decision = (While_Do) shape;
        } else if (shape instanceof Do_While) {
            INSTRUCTION = "DO";
            txtExpressionShape.setKeyword(Do_While.KEYWORD);
            this.decision = (Do_While) shape;
        }
        setTitle(Fi18N.get(INSTRUCTION + ".instruction.title"));
        Fi18N.loadMenuShapeHelp(lblHelp, INSTRUCTION + ".instruction");
        //Fi18N.loadTabTile(tabMain, INSTRUCTION + ".tab.instruction", 0);

        oldText = shape.getInstruction();
        memory = shape.algorithm.getMemory(shape.parent);
        
        txtExpressionShape.updateMenu(memory, shape.algorithm.getMyProgram());
        //-----------------------------------------
        if (this.decision.getInstruction().isEmpty()) {
            txtExpressionShape.setInstruction(" ");
            //txtExpressionShape.setInstruction(FkeyWord.get("TYPE.boolean.true"));
        } else {
            txtExpressionShape.setInstruction(this.decision.getInstruction());
        }
        txtComments.setText(this.decision.getComments());
        //-----------------------------------------
        //:::::::::::::::::::::::::::::::::::::::::
        //::::::::   Show Dialog  :::::::::::::::::
        setLocationRelativeTo(null);
        updateFont();
        this.setVisible(true);
        txtExpressionShape.requestFocus();
        //:::::::::::::::::::::::::::::::::::::::::
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tabMain = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextArea();
        lblHelp = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        btHelp = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtExpressionShape = new ui.flowchart.expression.TextExpression();

        jToggleButton1.setText("jToggleButton1");

        jButton3.setText("jButton3");

        jLabel3.setText("jLabel3");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        txtComments.setBackground(new java.awt.Color(204, 204, 204));
        txtComments.setColumns(20);
        txtComments.setRows(2);
        jScrollPane1.setViewportView(txtComments);

        tabMain.addTab("tab2", jScrollPane1);

        lblHelp.setText("help");
        lblHelp.setOpaque(true);
        tabMain.addTab("tab3", lblHelp);

        jPanel6.setLayout(new java.awt.GridLayout(1, 3, 10, 10));

        btOk.setText("ok");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });
        jPanel6.add(btOk);

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        jPanel6.add(btCancel);

        btHelp.setText("help");
        btHelp.setBorder(null);
        btHelp.setBorderPainted(false);
        btHelp.setContentAreaFilled(false);
        btHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHelpActionPerformed(evt);
            }
        });
        jPanel6.add(btHelp);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(tabMain)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtExpressionShape.setOpaque(true);
        jScrollPane4.setViewportView(txtExpressionShape);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        try {
            BreakMarks.checkParentesis(txtExpressionShape.getInstruction());
            decision.buildInstruction(txtExpressionShape.getInstruction(), txtComments.getText());
            decision.parseShape();
            decision.setSelected(false);
            setVisible(false);
        } catch (FlowchartException e) {
            e.setInstruction(txtExpressionShape.getInstruction());
            Fdialog.compileException(e);
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        decision.setInstruction(oldText);
        decision.setSelected(false);
        setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    private void btHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHelpActionPerformed
        Help.show(INSTRUCTION + ".instruction.www");
    }//GEN-LAST:event_btHelpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btHelp;
    private javax.swing.JButton btOk;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTextArea txtComments;
    private ui.flowchart.expression.TextExpression txtExpressionShape;
    // End of variables declaration//GEN-END:variables

}
