/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.dialogs.problems;

import flowchart.algorithm.Problem;
import flowchart.utils.UserName;
import flowchart.utils.image.ImageUtils;
import i18n.EditorI18N;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.TitledBorder;
import ui.FProperties;
import ui.dialogs.FMessages;

/**
 *
 * @author zulu
 */
public class ProblemEditor extends javax.swing.JFrame {

    UserName user = FProperties.getUser();
    Problem problem = null;

    /**
     * Creates new form ProblemEditor
     */
    public ProblemEditor() {
        initComponents();
        I18N();
        createNew("");

    }

    private void I18N() {
        setIconImage(EditorI18N.loadIcon("APPLICATION.icon", 24).getImage());
        setTitle(EditorI18N.get("PROBLEM_EDITOR.frame.title"));

        EditorI18N.loadResource(btNewFlux, "PROBLEM_EDITOR.button.new", 48);
        EditorI18N.loadResource(btOpenFile, "PROBLEM_EDITOR.button.load", 48);
        EditorI18N.loadResource(btSaveFileAs, "PROBLEM_EDITOR.button.saveAs", 48);

        pnTitle.setBorder(BorderFactory.createTitledBorder(EditorI18N.get("PROBLEM_EDITOR.problem.title")));
        pnDescription.setBorder(BorderFactory.createTitledBorder(EditorI18N.get("PROBLEM_EDITOR.problem.description")));
        pnInput.setBorder(BorderFactory.createTitledBorder(EditorI18N.get("PROBLEM_EDITOR.problem.input")));
        pnOutput.setBorder(BorderFactory.createTitledBorder(EditorI18N.get("PROBLEM_EDITOR.problem.output")));
        pnOutput.setBorder(BorderFactory.createTitledBorder(EditorI18N.get("PROBLEM_EDITOR.problem.output")));
        btImage.setToolTipText(EditorI18N.get("PROBLEM_EDITOR.problem.btImage.help"));
        setUser(user);
        txtPath.setText(System.getProperty("user.dir"));
        txtTitle.setFont(FProperties.getFont());
        txtInput.setFont(FProperties.getFont());
        txtOutput.setFont(FProperties.getFont());
        txtDescrption.setFont(FProperties.getFont());
    }

    public void createNew(String name) {
        if( name.isEmpty())
          name = Problem.FILE_DEFAULT_NAME;  
        
        pnProblem.repaint();
        txtTitle.setText("");
        txtInput.setText("");
        txtOutput.setText("");
        txtDescrption.setText("");
        btImage.setIcon(null);
        problem = new Problem();
        problem.setFileName(txtPath.getText() + File.separator + name);
        ((TitledBorder) pnProblem.getBorder()).setTitle(problem.getFileName());
        problem.save();
    }

    public void setUser(UserName newUser) {
        this.user = newUser;
        lblUserAvatar.setIcon(user.getAvatar());
        pnUserInfo.setBorder(BorderFactory.createTitledBorder(user.getName()));
        lblFullName.setText(user.getFullName());
        lblCode.setText(user.getCode());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPath = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        btNewFlux = new javax.swing.JButton();
        btOpenFile = new javax.swing.JButton();
        btSaveFileAs = new javax.swing.JButton();
        pnUserInfo = new javax.swing.JPanel();
        lblUserAvatar = new javax.swing.JLabel();
        lblCode = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPrroblemFiles = new javax.swing.JList();
        pnProblem = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        pnInput = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtInput = new javax.swing.JTextPane();
        pnOutput = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextPane();
        pnTitle = new javax.swing.JPanel();
        txtTitle = new javax.swing.JTextField();
        pnDescription = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDescrption = new javax.swing.JTextPane();
        btImage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPath.setEditable(false);
        txtPath.setBackground(new java.awt.Color(204, 204, 204));
        txtPath.setColumns(20);
        txtPath.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtPath.setForeground(new java.awt.Color(0, 0, 0));
        txtPath.setLineWrap(true);
        txtPath.setRows(5);
        jScrollPane3.setViewportView(txtPath);

        jPanel4.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        btNewFlux.setText("new");
        btNewFlux.setFocusable(false);
        btNewFlux.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNewFlux.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNewFlux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewFluxActionPerformed(evt);
            }
        });
        jPanel4.add(btNewFlux);

        btOpenFile.setText("open");
        btOpenFile.setFocusable(false);
        btOpenFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btOpenFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenFileActionPerformed(evt);
            }
        });
        jPanel4.add(btOpenFile);

        btSaveFileAs.setText("save As");
        btSaveFileAs.setFocusable(false);
        btSaveFileAs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSaveFileAs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSaveFileAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveFileAsActionPerformed(evt);
            }
        });
        jPanel4.add(btSaveFileAs);

        pnUserInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("UserName"));

        lblUserAvatar.setBackground(new java.awt.Color(204, 255, 255));
        lblUserAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserAvatar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblUserAvatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserAvatarMouseClicked(evt);
            }
        });

        lblCode.setText("code");

        lblFullName.setText("fullName");

        javax.swing.GroupLayout pnUserInfoLayout = new javax.swing.GroupLayout(pnUserInfo);
        pnUserInfo.setLayout(pnUserInfoLayout);
        pnUserInfoLayout.setHorizontalGroup(
            pnUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUserAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnUserInfoLayout.setVerticalGroup(
            pnUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserInfoLayout.createSequentialGroup()
                .addComponent(lblUserAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(lblFullName))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(pnUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3))
        );

        lstPrroblemFiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPrroblemFilesMouseClicked(evt);
            }
        });
        lstPrroblemFiles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstPrroblemFilesKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lstPrroblemFilesKeyTyped(evt);
            }
        });
        lstPrroblemFiles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPrroblemFilesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPrroblemFiles);

        pnProblem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FileName", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        pnInput.setBorder(javax.swing.BorderFactory.createTitledBorder("input"));
        pnInput.setLayout(new java.awt.BorderLayout());

        jScrollPane5.setViewportView(txtInput);

        pnInput.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jPanel6.add(pnInput);

        pnOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("output"));
        pnOutput.setLayout(new java.awt.BorderLayout());

        jScrollPane7.setViewportView(txtOutput);

        pnOutput.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jPanel6.add(pnOutput);

        pnTitle.setBorder(javax.swing.BorderFactory.createTitledBorder("Title"));
        pnTitle.setLayout(new java.awt.BorderLayout());
        pnTitle.add(txtTitle, java.awt.BorderLayout.CENTER);

        pnDescription.setBorder(javax.swing.BorderFactory.createTitledBorder("description"));
        pnDescription.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane6.setViewportView(txtDescrption);

        pnDescription.add(jScrollPane6);

        btImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImageActionPerformed(evt);
            }
        });
        pnDescription.add(btImage);

        javax.swing.GroupLayout pnProblemLayout = new javax.swing.GroupLayout(pnProblem);
        pnProblem.setLayout(pnProblemLayout);
        pnProblemLayout.setHorizontalGroup(
            pnProblemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        pnProblemLayout.setVerticalGroup(
            pnProblemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProblemLayout.createSequentialGroup()
                .addComponent(pnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnProblem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
            .addComponent(pnProblem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNewFluxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewFluxActionPerformed
        problem.save();
        String prob = FMessages.inputDialog("PROBLEM_EDITOR.inputDialog.new", EditorI18N.get("PROBLEM_EDITOR.problem.file.default"));
        createNew(prob);
    }//GEN-LAST:event_btNewFluxActionPerformed

    private void btOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenFileActionPerformed

    }//GEN-LAST:event_btOpenFileActionPerformed

    private void btSaveFileAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveFileAsActionPerformed

    }//GEN-LAST:event_btSaveFileAsActionPerformed

    private void lblUserAvatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserAvatarMouseClicked

    }//GEN-LAST:event_lblUserAvatarMouseClicked

    private void lstPrroblemFilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPrroblemFilesMouseClicked


    }//GEN-LAST:event_lstPrroblemFilesMouseClicked

    private void lstPrroblemFilesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstPrroblemFilesKeyPressed

    }//GEN-LAST:event_lstPrroblemFilesKeyPressed

    private void lstPrroblemFilesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstPrroblemFilesKeyTyped

    }//GEN-LAST:event_lstPrroblemFilesKeyTyped

    private void lstPrroblemFilesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPrroblemFilesValueChanged

    }//GEN-LAST:event_lstPrroblemFilesValueChanged

    private void btImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImageActionPerformed
        ImageIcon img = ImageUtils.selectImageFromFile();
        if (img != null) {
            img = ImageUtils.resizeProportional(img, 300, 200);
            btImage.setIcon(img);
        }
    }//GEN-LAST:event_btImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProblemEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProblemEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProblemEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProblemEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProblemEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btImage;
    private javax.swing.JButton btNewFlux;
    private javax.swing.JButton btOpenFile;
    private javax.swing.JButton btSaveFileAs;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblUserAvatar;
    private javax.swing.JList lstPrroblemFiles;
    private javax.swing.JPanel pnDescription;
    private javax.swing.JPanel pnInput;
    private javax.swing.JPanel pnOutput;
    private javax.swing.JPanel pnProblem;
    private javax.swing.JPanel pnTitle;
    private javax.swing.JPanel pnUserInfo;
    private javax.swing.JTextPane txtDescrption;
    private javax.swing.JTextPane txtInput;
    private javax.swing.JTextPane txtOutput;
    private javax.swing.JTextArea txtPath;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
