FUNCTION VOID imprime ROUND_OPEN INTEGER x[] ROUND_CLOSE
        ITERATE INTEGER i1 FROM 0 TO ELEMENTS_OF ROUND_OPEN x ROUND_CLOSE SUB 1 STEP 1
            WRITE " " SUM x[i1]
        END ITERATE
        WRITE "\n"
    END imprime
