FUNCTION VOID imprime2D ROUND_OPEN INTEGER x[] ROUND_CLOSE
        ITERATE INTEGER i FROM 0 TO ELEMENTS_OF ROUND_OPEN x ROUND_CLOSE SUB 1 STEP 1
            ITERATE INTEGER y FROM 0 TO ELEMENTS_OF ROUND_OPEN x[i] ROUND_CLOSE SUB 1 STEP 1
                WRITE x[i][y] SUM " "
            END ITERATE
            WRITE "\n"
        END ITERATE
    END imprime2D
