FUNCTION VOID inicia ROUND_OPEN INTEGER x[] ROUND_CLOSE
        ITERATE INTEGER i1 FROM 0 TO ELEMENTS_OF ROUND_OPEN x ROUND_CLOSE SUB 1 STEP 1
            EXECUTE x SQUARE_OPEN i1  SQUARE_CLOSE SET INT ROUND_OPEN RANDOM ROUND_OPEN ROUND_CLOSE MULT ELEMENTS_OF ROUND_OPEN x ROUND_CLOSE ROUND_CLOSE
        END ITERATE
    END inicia
