FUNCTION VOID inicia2D ROUND_OPEN INTEGER x[] ROUND_CLOSE
        ITERATE INTEGER i FROM 0 TO ELEMENTS_OF ROUND_OPEN x ROUND_CLOSE SUB 1 STEP 1
            ITERATE INTEGER y FROM 0 TO ELEMENTS_OF ROUND_OPEN x[i] ROUND_CLOSE SUB 1 STEP 1
                EXECUTE x SQUARE_OPEN i  SQUARE_CLOSE SQUARE_OPEN y  SQUARE_CLOSE SET INT ROUND_OPEN RANDOM ROUND_OPEN ROUND_CLOSE MULT 10 ROUND_CLOSE
            END ITERATE
        END ITERATE
    END inicia2D
